# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      non-oracle-rust-dependencies:
        patterns: ["*"]
        exclude-patterns: ["cudarc", "rocmrc"]
    ignore:
      - dependency-name: cudarc
      - dependency-name: rocmrc
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
